server:
  port: 8081
  address: 0.0.0.0
  tomcat:
    allow-host-header-injection: true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user_service_role
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_service_schema
jwt:
  SECRET_KEY: 316e64aab9e61fdcd3bfd0fccab9079ffe2deec4249084fa2d72915f
  EXPIRATION: 3600000
  REFRESH_TOKEN_EXPIRATION: 604800000