server:
  port: 8089

spring:
  application:
    name: quiz

#  data:
#    mongodb:
#      uri: mongodb://185.112.102.127:27017/quiz_db

  datasource:
    #url: jdbc:mysql://185.112.102.127:3308/quiz_db?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/quiz_db?useSSL=false&serverTimezone=UTC
    username: ilswm
    password: Greenaple1Q!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
